---
- hosts: centos_nodes
  become: yes
  tasks:
    - name: Create /tmp/kube directory
      file:
        path: /tmp/kube
        state: directory
        mode: '0755'
    
    - name: Copy kubeconfig from Ansible server
      copy:
        src: /tmp/kube/config
        dest: /tmp/kube/config
        mode: '0600'
    
    - name: Create Kubernetes deployment using kubectl
      shell: |
        export KUBECONFIG=/tmp/kube/config
        /usr/local/bin/kubectl apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{ deployment_name }}
          namespace: {{ k8s_namespace }}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: webapp
          template:
            metadata:
              labels:
                app: webapp
            spec:
              containers:
              - name: webapp-container
                image: {{ docker_image }}
                ports:
                - containerPort: 8080
        EOF
