apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80         # The port you want to expose externally
      targetPort: 8084 # The port your container listens on (Tomcat)
  type: NodePort      # Exposes the service on a port on each node

